### ISSUE TITLE
Disappearing playtime information in Game Overview

### ISSUE THREAD

**Issue by ma3a** [ma3a/SDH-PlayTime#12]
Some users reports, that this screen a bit buggy: 
![image](https://user-images.githubusercontent.com/6958374/226604562-ec198eb4-e0d7-4c6b-8027-a7d069c2aa3b.png)

**Comment by SilentException** [comment]
My take. It is working in non-deterministic way :)
https://streamable.com/ygntwg

**Comment by ma3a** [comment]
[SDH-PlayTime-1.0.0.zip](https://github.com/ma3a/SDH-PlayTime/files/11185123/SDH-PlayTime-1.0.0.zip)

**Comment by SilentException** [comment]
Thanks, could you also push to testing?
