### ISSUE TITLE
Previous play time of games played before installing plugin being overwritten in Library

### ISSUE THREAD

**Issue by LittleDoDonk** [ma3a/SDH-PlayTime#22]
In the Library when sorting by "Hours Played", if I play a game after installing the PlayTime plugin, it will only show the amount of time played since installing the plugin, overwriting the playtime the game had previously. Clicking on the game and going to its page will display the full correct time.

For example on A Hat in Time I had 19.5 hours of playtime before installing the plugin. After installing the plugin and playing the game, the time in the Library changed to 15.2 minutes. Clicking the game page shows the correct full time of 19.6 hours. Ideally, the Library would also show the full 19.6 hours.

**Comment by ma3a** [comment]
Oh, nice bug!
Probably we should also migrate from steam games as well, to be able to show playtime correctly!
