### ISSUE TITLE
Cannot find the plugin (but would love to)

### ISSUE THREAD

**Issue by Maz111111** [ma3a/SDH-PlayTime#27]
The plugin cannot be found in the test store, nor in the default store, nor under https://plugins.deckbrew.xyz/.
Am I doing something wrong?
I tried to set https://plugins.deckbrew.xyz/ as a custom store but without success. Even if I click on the link (https://plugins.deckbrew.xyz/) on the Github page in the browser on the PC, I can't find the plugin.
The Discord link you provided in #16 leads to Nirvana (Discord reports "No text channels"). So I don't know where else to ask.
Thank you for the great work

**Comment by ma3a** [comment]
Probably this is my bad - need to add clarity, that it haven't been published yet. But we have our own Discord channel, and right now there is an release section in this project repo where you could find zip file for installing it manually. 

Hope in this month it will be published (need to add additional things before publishing)

**Comment by geenaxion** [comment]
What's the discord link?

**Comment by ma3a** [comment]
https://discord.com/channels/960281551428522045/960284126701813770

**Comment by ma3a** [comment]
https://discord.com/channels/960281551428522045/1087800823846813716

**Comment by geenaxion** [comment]
No text channel showing up.

I just want to ask since i find it weird,  ive been using playtime plugin for weeks.
It just recently dont work, i tried installing manually it wont show up anymore.

**Comment by ma3a** [comment]
As I mentioned before - there is an release section in main github page of the project, where you could find latest release. Sometimes steam release new version, and all plugins have to updated because of that. 


> No text channel showing up.
Please try to use official li[n](https://discord.com/invite/U88fbeHyzt)k then from [decky loader website](https://decky.xyz)

**Comment by geenaxion** [comment]
I found your fix at  discord,  I can't comment there yet so I'm just gonna say it here.
Thank you
