### ISSUE TITLE
Long time storage

### ISSUE THREAD

**Issue by SilentException** [ma3a/SDH-PlayTime#3]
Noticed that you increased the maximum history time to one year. I would like to propose a different solution because it is still not good to loose total playtime after one year.

The detailed statistic can be stored for a month or maybe more (as is now - a year) but instead of deleting the records, group the statistics and add the sum that was to be deleted to long time storage (simple key value pair appid=old_playtime). That way you still have statistics but also can calculate total play time for game info screen that never gets deleted.

**Comment by ma3a** [comment]
Thank you for the feedback! 
I think we've just implement it  - [Migrate to SQL](https://github.com/ma3a/SDH-PlayTime/commit/838dba955b1046e7d43e50c00a911b18c5a6daf0)

So with that change, there is no restrictions at all :)

**Comment by SilentException** [comment]
Thats great, thanks! If I'm reading it correctly the playtime statistics (per session) are saved together with overall play time. I like that, the statistics can be safely purged without touching the overall (y)

Now I only need to figure out how to transfer play times from Steamless Times to overall_time table. Guess the process should be quite strightforward: get appId/name from id Steamless Times is using and then insert values in game_dict table and overall_time table :)

**Comment by SilentException** [comment]
Yes, I'm quite certain I could do it manually but glad to hear you're doing GUI migration. That's awesome thanks. Will try it when is available on testing repo.
