### ISSUE TITLE
How to remove the plugin?

### ISSUE THREAD

**Issue by handsome1987** [ma3a/SDH-PlayTime#33]
How can i remove the plugin?
Because when i wanted to remove it from decky it will be back after restart of shutdown and start the steamdeck.

**Comment by ma3a** [comment]
Hmm probably just remove should works, but it is strange. Suggesting to ask this question in [decky-loader](https://discord.com/channels/960281551428522045/960284126701813770) discord, because this plugin is not controlling addition / removal itself.
