### ISSUE TITLE
backup and / or sync play time to another device

### ISSUE THREAD

**Issue by nioncode** [ma3a/SDH-PlayTime#49]
It would be great if there would be a way to synchronize the play time between multiple devices.

I'm not much of a steam user on Windows, so I don't know if this makes sense, but is there a way to track the play time of non-steam games on Windows and then sync the play time with the one on the steam deck?

My scenario is that I sometimes play games on Windows and then continue them on the steam deck and vice-versa (and sync the save games between them). I think as a first shot it would be good enough if there is a clear documentation about what files to back up from which folder (which can then be done with syncthing, rsync, or whatever tool the user likes to use) so that the play time can be backed up and then I can tackle tracking the play time on Windows to also add it to the database.

**Comment by ma3a** [comment]
> It would be great if there would be a way to synchronize the play time between multiple devices.

Very hard to implement request. It requires writing clients for each platform (device). And probably would not be implemented in observable future. 

If I have some time - will try to create a wiki pages for how-to's.

All the data Playtime stores is in Sqlite database, which is located in `/home/deck/homebrew/data/SDH-PlayTime/storage.db`. There are a lot of tools that could view / change. But be careful with all changes, if you gonna sync changed file back to SteamDeck, it could leads to plugin crash if data in wrong format. You could use any tools you like (rsync, decky plugins for cloud saving) for this file.
