### ISSUE TITLE
Unable to save manually adjusted time

### ISSUE THREAD

**Issue by Corgi** [ma3a/SDH-PlayTime#55]
Hi! I'm trying to adjust playtime on a non-Steam entry and can't seem to get it to stick. After inputting my time there doesn't seem to be a way to save the new time, and it reverts if I back out of the menu. I'm not sure what I need to provide in terms of data for this bug but let me know what might be needed and I can dig it up.

**Comment by ma3a** [comment]
Please reach out in [discord](https://github.com/ma3a/SDH-PlayTime#contact) channel to me, and it would be helpful if you provide screenshots.
