### ISSUE TITLE
This plugin seemingly can't perform well in steam os 3.5.7!

### ISSUE THREAD

**Issue by er0miu** [ma3a/SDH-PlayTime#56]
My steamdeck is LCD and updated with the latest stable version.
I don't know if it's just me or 3.5.7 version update that's causing the plugin to not work. 

Since I often play a lot of non steam games, this plugin is very useful for me. However, I don't know Linux myself and I'm not good at English, so it's great to be able to download this plugin easily from the plugin shop. Thank you for your selflessness!
I hope you understand what I've written through the translator, and best wishes!

**Comment by 1basti1** [comment]
My Plugin works fine with 3.5.7

**Comment by ma3a** [comment]
Same for me - version from plugin store works fine for me as well.
@er0miu , could you provide more information like screenshots (photos will work as well)?

**Comment by er0miu** [comment]
The first to sixth pictures show the plugin running as it is. 
The first picture should show the game time but it doesn't.
The entire content of the plugin is always displayed as "loading".
I've tried reinstalling the plugin several times, but it doesn't work.
![1](https://github.com/ma3a/SDH-PlayTime/assets/153077193/682297cf-059e-4054-94cf-d8722d207356)
![2](https://github.com/ma3a/SDH-PlayTime/assets/153077193/2cee1002-251a-4e6b-aa6a-ab2a86b33b6c)
![3](https://github.com/ma3a/SDH-PlayTime/assets/153077193/37b2d1ef-d4be-4d7f-9dff-d043b62b6a50)
![4](https://github.com/ma3a/SDH-PlayTime/assets/153077193/b536c40a-9e07-474a-8238-795a2a998f04)
![5](https://github.com/ma3a/SDH-PlayTime/assets/153077193/75fc477b-1aba-49bf-a5dd-cbc18d8fe9e0)
![6](https://github.com/ma3a/SDH-PlayTime/assets/153077193/7d5dc061-346f-4255-8e29-bcb79115afdd)
The seventh and eighth pictures reflect the plugins I have installed.
![7](https://github.com/ma3a/SDH-PlayTime/assets/153077193/a136ea84-9a79-4e62-b416-d01109ab2286)
![8](https://github.com/ma3a/SDH-PlayTime/assets/153077193/3198f8db-109e-4e66-9414-c1a1e4d17355)
The ninth and tenth pictures reflect basic information about my machine.
![9](https://github.com/ma3a/SDH-PlayTime/assets/153077193/3232a229-ffc4-417e-bbb4-de1c8432db30)
![10](https://github.com/ma3a/SDH-PlayTime/assets/153077193/1c7cff8c-5cfe-4934-ad73-1a982002dec3)

I hope this information will be helpful to you.If you need additional information, I'd be happy to provide.
Thank you very much for your attention!

**Comment by ma3a** [comment]
Hmmm got same Steam UI version, Steam OS version, and just reinstalled it from store. Could you try to click "Reload" and "Reinstall" if it doesn't help?
You could find this options in Decky Loader setting in plugins menu.

If this doesn't help, could you try to restart your Deck? 
If this doesn't help, probably I need to get logs from you, and they located here: `~/homebrew/logs/SDH-PlayTime/decky-playtime.log`

**Comment by ma3a** [comment]
Checked logs, and one of the users have the same problem as you do, 4 months ago. 
[Discord server](https://decky.xyz/discord)
[Link to the message, will be visible after joining the server](https://discord.com/channels/960281551428522045/1087800823846813716/1133863380390789261)

Can you show which Decky Version you are, and on which channel (stable, dev)

**Comment by er0miu** [comment]
![IMG_20231209_020306](https://github.com/ma3a/SDH-PlayTime/assets/153077193/f2c62b40-431a-4edc-b91f-974e5e32e6e8)
![IMG_20231209_020210](https://github.com/ma3a/SDH-PlayTime/assets/153077193/7897b156-4742-4feb-9fe7-ce7fa1344286)

**Comment by 1basti1** [comment]
I'm pretty sure you have to update decky loader. Newest stable is 2.10.5 I think

**Comment by 1basti1** [comment]
Yes, I just looked, the SQLite fix (which ma3a mentioned) was fixed after your version (2.10.3) came out.

**Comment by er0miu** [comment]
@1basti1 You're right! What's very strange is that my decky loader hasn't been able to receive updates for the past few months. Even when I click the update button multiple times it doesn't respond. After your reminder, I updated it using github and now the plugin works successfully.
@ma3a @1basti1 Thank you both very much for your efforts! Your activity makes this community better!

**Comment by 1basti1** [comment]
No problem. Glad it works now. Have fun :)

And why decky didn't update itself. I don't know unfortunately.
