### ISSUE TITLE
not working after last SteamOS update

### ISSUE THREAD

**Issue by dszubov** [ma3a/SDH-PlayTime#6]
![IMG_0849](https://user-images.githubusercontent.com/104792259/225726475-6d8efc80-f561-425a-a769-48e100b49bd4.jpeg)

**Comment by CalebGitBritannia** [comment]
Hi, I have been having this issue as well. I cannot get the plugin to work with the latest update

**Comment by ma3a** [comment]
This is because we haven't updated our plugin in repository for testing:
https://github.com/SteamDeckHomebrew/decky-plugin-database/pull/272
Just updated it, so after build passed, you should be able to get a fresh version from testing respository
