### ISSUE TITLE
Plugin stopped working after the recent SteamOS update

### ISSUE THREAD

**Issue by Sythog** [ma3a/SDH-PlayTime#60]
Having the same issue as described in the #56 
The play time is not counted and the plugin UI infinitely loading. 
Sometimes, it throws an error 
```
TypeError: plugin_exports.default is not a function
  at PluginLoader.importReactPlugin
  at async PluginLoader.importPlugin
```

|   |   |
|---|---|
| SteamOS version | 3.6.8 |
| Steam version | 1719967667 | 
| Decky version | v3.0.0-pre2 |
| Plugin version | 1.0.0-1 |

**Comment by Sythog** [comment]
@ma3a the link gives me 404 :disappointed:

**Comment by ma3a** [comment]
[SDH-PlayTime-1.0.2.zip](https://github.com/user-attachments/files/16085701/SDH-PlayTime-1.0.2.zip)
Strange, this a ZIP file from release

**Comment by Sythog** [comment]
It worked! Thank you for the quick fix!
