### ISSUE TITLE
One game title missing from playtime charts

### ISSUE THREAD

**Issue by midnightcatwalk** [ma3a/SDH-PlayTime#65]
This is on a Stable, up-to-date Deck

One of my games is missing its title in the playtime charts (see attached photo for an example from the weekly chart; the same is true for other charts). It’s Scrabble Journey, a non-Steam game running through Lutris. None of my other Lutris games (or any other games for that matter) have this issue. It also only happens intermittently for this game.

![IMG_5261](https://github.com/user-attachments/assets/38ed4a7c-3a50-4c36-b016-0a103bf72af8)

Any idea what could be causing this?

**Comment by ma3a** [comment]
Is it visible in other reports? By months / Overall?

**Comment by midnightcatwalk** [comment]
It is, or rather was. Restarting seems to have fixed it, even though it didn’t before. I think I just overreacted to a transitory bug.
